#!/usr/bin/env bash
# Build/check the DiracQ GPUI surfaces (crates/diracq_gpui) against the vendored
# GPUI. These views link Zed's `gpui` crate, which uses Zed's workspace
# inheritance — so the crate must be built *as a member of the vendored Zed
# workspace*. Cargo requires members to live under the workspace root, so this
# script stages a copy of crates/diracq_gpui into third_party/zed/crates/ (the
# committed source under crates/diracq_gpui remains the source of truth).
#
# Requirements:
#   1. a vendored Zed (scripts/vendor-zed.sh),
#   2. Rust 1.95.0 (Zed's pin; see rust-toolchain.toml),
#   3. GPUI's Linux system libraries (xkbcommon, wayland, vulkan, xcb, …).
#
# This is deliberately separate from the standalone `cargo check --workspace`,
# which never needs Zed or a GPU.
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$root"
zed="third_party/zed"

# 1. Vendor Zed if missing.
if [ ! -d "$zed/crates/gpui" ]; then
  echo "[build-gpui] vendoring Zed first…"
  bash scripts/vendor-zed.sh
fi

# 2. GPUI Linux system dependencies (Debian/Ubuntu names).
if command -v apt-get >/dev/null 2>&1; then
  echo "[build-gpui] ensuring GPUI system libs…"
  SUDO=""; [ "$(id -u)" -ne 0 ] && SUDO="sudo"
  $SUDO apt-get install -y \
    libxkbcommon-dev libxkbcommon-x11-dev libwayland-dev libvulkan-dev libxcb1-dev \
    libfontconfig-dev libfreetype-dev 2>/dev/null \
    || echo "[build-gpui] WARN: could not install system libs automatically"
fi

# 3. Stage diracq_gpui inside the Zed workspace with build-correct paths.
staged="$zed/crates/diracq_gpui"
echo "[build-gpui] staging $staged …"
rm -rf "$staged" && mkdir -p "$staged/src"
cp crates/diracq_gpui/src/lib.rs "$staged/src/lib.rs"
cat > "$staged/Cargo.toml" <<EOF
# AUTO-GENERATED by scripts/build-gpui.sh — edit crates/diracq_gpui instead.
[package]
name = "diracq_gpui"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
gpui = { path = "../gpui" }
diracq_services = { path = "$root/crates/diracq_services" }
diracq_viz = { path = "$root/crates/diracq_viz" }
diracq_selene = { path = "$root/crates/diracq_selene" }
EOF

# 4. Register it as a member of the vendored Zed workspace (idempotent).
python3 - "$zed/Cargo.toml" <<'PY'
import pathlib, sys
p = pathlib.Path(sys.argv[1]); t = p.read_text()
if '"crates/diracq_gpui"' not in t:
    t = t.replace("members = [\n", 'members = [\n    "crates/diracq_gpui",\n', 1)
    p.write_text(t)
    print("[build-gpui] registered diracq_gpui in the Zed workspace")
PY

# 5. Check the GPUI views against the pinned toolchain.
echo "[build-gpui] cargo check diracq_gpui (Rust 1.95.0)…"
( cd "$zed" && RUSTUP_TOOLCHAIN=1.95.0 cargo check -p diracq_gpui )

echo "[build-gpui] OK — GPUI surfaces type-check against the vendored gpui."
